"""init_db

Revision ID: c725ad99771a
Revises: 559bb671d134
Create Date: 2024-07-02 15:43:36.781933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c725ad99771a'
down_revision: Union[str, None] = '559bb671d134'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletas', sa.Column('centro_treinamento_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'atletas', 'centros_treinamento', ['centro_treinamento_id'], ['pk_id'])
    op.create_unique_constraint(None, 'categorias', ['nome'])
    op.add_column('centros_treinamento', sa.Column('proprietario', sa.String(length=30), nullable=False))
    op.drop_constraint('centros_treinamento_atleta_id_fkey', 'centros_treinamento', type_='foreignkey')
    op.drop_constraint('centros_treinamento_proprietario_id_fkey', 'centros_treinamento', type_='foreignkey')
    op.drop_column('centros_treinamento', 'proprietario_id')
    op.drop_column('centros_treinamento', 'atleta_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('centros_treinamento', sa.Column('atleta_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('centros_treinamento', sa.Column('proprietario_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('centros_treinamento_proprietario_id_fkey', 'centros_treinamento', 'atletas', ['proprietario_id'], ['pk_id'])
    op.create_foreign_key('centros_treinamento_atleta_id_fkey', 'centros_treinamento', 'atletas', ['atleta_id'], ['pk_id'])
    op.drop_column('centros_treinamento', 'proprietario')
    op.drop_constraint(None, 'categorias', type_='unique')
    op.drop_constraint(None, 'atletas', type_='foreignkey')
    op.drop_column('atletas', 'centro_treinamento_id')
    # ### end Alembic commands ###
